version: '3.8'

services:
  eureka:
    build: eureka
    container_name: eureka-server
    ports:
      - "8761:8761"

  auth:
    build: auth
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_DISCOVERY_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres-auth
      - eureka

  postgres-auth:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  postgres-recommendation:
    image: postgres:16
    environment:
      POSTGRES_DB: recommendation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"


  recommendation:
    build: recommendation
    container_name: recommendation-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_DISCOVERY_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
      - AI_SERVICE_URL= # Сюда url АИшки
    depends_on:
      - eureka
      - postgres-recommendation

  gateway:
    build: gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_DISCOVERY_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - auth
      - recommendation