version: '3.8'

services:
  auth:
    build: auth
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET= # Сюда сгенерированный токен
    depends_on:
      - postgres-auth
  #    networks:
#      - muzrec-network

  postgres-auth:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  recommendation:
    build: recommendation
    container_name: recommendation-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AI_SERVICE_URL= # Сюда url АИшки
#    networks:
#      - muzrec-network

  gateway:
    build: gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET= # Сюда сгенерированный токен
    depends_on:
      - auth
      - recommendation
#    networks:
#      - muzrec-network

#  networks:
#    muzrec-network.driver: bridge