spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: recommendation-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/recommendation/**

        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}