spring:
  application:
    name: recommendation

  r2dbc:
    url: r2dbc:postgresql://postgres-recommendation:5432/recommendation_db
    username: postgres
    password: postgres
    initialization-mode: always

  sql:
    init:
      mode: always

    flyway:
      enabled: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

ai-service:
  url: ${AI_SERVICE_URL} # Сюда пишешь свой адрес Python-сервиса

logging:
  level:
    org.postgres: DEBUG
    root: INFO
    com.muzrec: DEBUG